name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build backend image
        run: docker build -t typesetting-mis-backend:${{ github.sha }} ./backend
      
      - name: Build frontend image
        run: docker build -t typesetting-mis-frontend:${{ github.sha }} ./frontend
      
      - name: Push images (if registry configured)
        if: ${{ secrets.REGISTRY != '' }}
        run: |
          docker tag typesetting-mis-backend:${{ github.sha }} ${{ secrets.REGISTRY }}/typesetting-mis-backend:${{ github.sha }}
          docker tag typesetting-mis-frontend:${{ github.sha }} ${{ secrets.REGISTRY }}/typesetting-mis-frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY }}/typesetting-mis-backend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY }}/typesetting-mis-frontend:${{ github.sha }}